package com.example.data.remote

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.Interceptor
import okhttp3.OkHttpClient
import retrofit2.Response
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.*
import java.util.concurrent.TimeUnit

import com.example.BuildConfig

/**
 * Real backend client for PulaRide.
 *
 * Everything here talks to a real Supabase project (free tier):
 *  - Auth: email OTP (real, free). SMS OTP would need a paid Twilio/Vonage provider.
 *  - Data: Postgres tables accessed over the REST API.
 *  - "Realtime" is implemented via short-interval polling of the REST API. This is
 *    genuinely real data from the server, free, and avoids the fragile WS handshake.
 *
 * Credentials come from BuildConfig (generated by the secrets-gradle-plugin from .env).
 * If .env is missing, .env.example supplies placeholder values so the app still compiles.
 */

object SupabaseConfig {
    val url: String = BuildConfig.SUPABASE_URL.trimEnd('/')
    val anonKey: String = BuildConfig.SUPABASE_ANON_KEY
}

// ---- Moshi models ---------------------------------------------------------

@JsonClass(generateAdapter = true)
data class AuthOtpRequest(
    val email: String,
    @Json(name = "should_create_user") val shouldCreateUser: Boolean = true
)

@JsonClass(generateAdapter = true)
data class AuthVerifyRequest(
    val type: String = "email",
    val email: String,
    val token: String
)

@JsonClass(generateAdapter = true)
data class AuthSession(
    @Json(name = "access_token") val accessToken: String? = null,
    @Json(name = "refresh_token") val refreshToken: String? = null,
    val user: AuthUser? = null
)

@JsonClass(generateAdapter = true)
data class AuthUser(
    val id: String? = null,
    val email: String? = null
)

@JsonClass(generateAdapter = true)
data class ProfileRow(
    val id: String? = null,
    val name: String? = null,
    val phone: String? = null,
    val role: String? = null
)

@JsonClass(generateAdapter = true)
data class DriverRow(
    val id: String? = null,
    @Json(name = "user_id") val userId: String? = null,
    val name: String? = null,
    val lat: Double? = null,
    val lng: Double? = null,
    val available: Boolean? = null,
    @Json(name = "vehicle_model") val vehicleModel: String? = null,
    @Json(name = "vehicle_plate") val vehiclePlate: String? = null,
    val rating: Double? = null,
    @Json(name = "is_female") val isFemale: Boolean? = null,
    @Json(name = "last_updated") val lastUpdated: String? = null
)

@JsonClass(generateAdapter = true)
data class DriverUpsert(
    @Json(name = "user_id") val userId: String,
    val name: String,
    val lat: Double,
    val lng: Double,
    val available: Boolean,
    @Json(name = "vehicle_model") val vehicleModel: String,
    @Json(name = "vehicle_plate") val vehiclePlate: String,
    val rating: Double,
    @Json(name = "is_female") val isFemale: Boolean
)

@JsonClass(generateAdapter = true)
data class RideRequestRow(
    val id: String? = null,
    @Json(name = "rider_id") val riderId: String? = null,
    @Json(name = "pickup_lat") val pickupLat: Double? = null,
    @Json(name = "pickup_lng") val pickupLng: Double? = null,
    @Json(name = "dropoff_lat") val dropoffLat: Double? = null,
    @Json(name = "dropoff_lng") val dropoffLng: Double? = null,
    @Json(name = "offered_fare") val offeredFare: Double? = null,
    val status: String? = null,
    @Json(name = "created_at") val createdAt: String? = null
)

@JsonClass(generateAdapter = true)
data class RideRequestInsert(
    @Json(name = "rider_id") val riderId: String,
    @Json(name = "pickup_lat") val pickupLat: Double,
    @Json(name = "pickup_lng") val pickupLng: Double,
    @Json(name = "dropoff_lat") val dropoffLat: Double,
    @Json(name = "dropoff_lng") val dropoffLng: Double,
    @Json(name = "offered_fare") val offeredFare: Double,
    val status: String = "OPEN"
)

@JsonClass(generateAdapter = true)
data class BidRow(
    val id: String? = null,
    @Json(name = "request_id") val requestId: String? = null,
    @Json(name = "driver_id") val driverId: String? = null,
    @Json(name = "driver_name") val driverName: String? = null,
    @Json(name = "vehicle_model") val vehicleModel: String? = null,
    @Json(name = "vehicle_plate") val vehiclePlate: String? = null,
    val rating: Double? = null,
    @Json(name = "bid_amount") val bidAmount: Double? = null,
    @Json(name = "eta_minutes") val etaMinutes: Int? = null,
    @Json(name = "is_female") val isFemale: Boolean? = null,
    val status: String? = null
)

@JsonClass(generateAdapter = true)
data class BidInsert(
    @Json(name = "request_id") val requestId: String,
    @Json(name = "driver_id") val driverId: String,
    @Json(name = "driver_name") val driverName: String,
    @Json(name = "vehicle_model") val vehicleModel: String,
    @Json(name = "vehicle_plate") val vehiclePlate: String,
    val rating: Double,
    @Json(name = "bid_amount") val bidAmount: Double,
    @Json(name = "eta_minutes") val etaMinutes: Int,
    @Json(name = "is_female") val isFemale: Boolean,
    val status: String = "PENDING"
)

@JsonClass(generateAdapter = true)
data class MessageRow(
    val id: String? = null,
    @Json(name = "ride_id") val rideId: String? = null,
    @Json(name = "sender_id") val senderId: String? = null,
    @Json(name = "sender_name") val senderName: String? = null,
    val body: String? = null,
    @Json(name = "created_at") val createdAt: String? = null
)

@JsonClass(generateAdapter = true)
data class MessageInsert(
    @Json(name = "ride_id") val rideId: String,
    @Json(name = "sender_id") val senderId: String,
    @Json(name = "sender_name") val senderName: String,
    val body: String
)

@JsonClass(generateAdapter = true)
data class RideCreatedRow(
    val id: String? = null
)

@JsonClass(generateAdapter = true)
data class RideInsert(
    @Json(name = "request_id") val requestId: String,
    @Json(name = "driver_id") val driverId: String,
    @Json(name = "rider_id") val riderId: String,
    val status: String = "EN_ROUTE_PICKUP",
    val fare: Double
)

// ---- Retrofit API ---------------------------------------------------------

interface SupabaseApi {
    @POST("/auth/v1/otp")
    suspend fun sendOtp(@Body body: AuthOtpRequest): Response<Unit>

    @POST("/auth/v1/verify")
    suspend fun verifyOtp(@Body body: AuthVerifyRequest): Response<AuthSession>

    @GET("/auth/v1/user")
    suspend fun getUser(@Header("Authorization") bearer: String): Response<AuthUser>

    @GET("/rest/v1/drivers")
    suspend fun getAvailableDrivers(
        @Header("Authorization") bearer: String,
        @Query("available", encoded = true) available: String = "eq.true",
        @Query("select", encoded = true) select: String = "*",
        @Query("order", encoded = true) order: String = "last_updated.desc"
    ): Response<List<DriverRow>>

    @POST("/rest/v1/drivers")
    suspend fun upsertDriver(
        @Header("Authorization") bearer: String,
        @Header("Prefer") prefer: String = "resolution=merge-duplicates,return=minimal",
        @Body body: DriverUpsert
    ): Response<Unit>

    @POST("/rest/v1/ride_requests")
    suspend fun createRideRequest(
        @Header("Authorization") bearer: String,
        @Header("Prefer") prefer: String = "return=representation",
        @Body body: RideRequestInsert
    ): Response<List<RideRequestRow>>

    @GET("/rest/v1/bids")
    suspend fun getBids(
        @Header("Authorization") bearer: String,
        @Query("request_id", encoded = true) requestId: String,
        @Query("select", encoded = true) select: String = "*",
        @Query("order", encoded = true) order: String = "created_at.asc"
    ): Response<List<BidRow>>

    @POST("/rest/v1/bids")
    suspend fun createBid(
        @Header("Authorization") bearer: String,
        @Header("Prefer") prefer: String = "return=minimal",
        @Body body: BidInsert
    ): Response<Unit>

    @POST("/rest/v1/rides")
    suspend fun createRide(
        @Header("Authorization") bearer: String,
        @Header("Prefer") prefer: String = "return=representation",
        @Body body: RideInsert
    ): Response<List<RideCreatedRow>>

    @GET("/rest/v1/messages")
    suspend fun getMessages(
        @Header("Authorization") bearer: String,
        @Query("ride_id", encoded = true) rideId: String,
        @Query("select", encoded = true) select: String = "*",
        @Query("order", encoded = true) order: String = "created_at.asc"
    ): Response<List<MessageRow>>

    @POST("/rest/v1/messages")
    suspend fun sendMessage(
        @Header("Authorization") bearer: String,
        @Header("Prefer") prefer: String = "return=minimal",
        @Body body: MessageInsert
    ): Response<Unit>
}

// ---- Auth token holder + client ------------------------------------------

object SupabaseClient {
    var accessToken: String? = null
        private set

    fun setSession(token: String?) {
        accessToken = token
    }

    fun authHeader(): String = "Bearer ${accessToken ?: SupabaseConfig.anonKey}"

    private val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()

    private val client = OkHttpClient.Builder()
        .connectTimeout(20, TimeUnit.SECONDS)
        .readTimeout(20, TimeUnit.SECONDS)
        .addInterceptor(Interceptor { chain ->
            val req = chain.request().newBuilder()
                .addHeader("apikey", SupabaseConfig.anonKey)
                .build()
            chain.proceed(req)
        })
        .build()

    val api: SupabaseApi by lazy {
        Retrofit.Builder()
            .baseUrl("${SupabaseConfig.url}/")
            .client(client)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(SupabaseApi::class.java)
    }
}
